name: test-workflow

on: [push]

jobs:
  test-workflow-features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo ${{ toJson(github.head_ref) }}
    - name: printing cotext values
      run: |
        echo "${{ github.ref }}"
        echo ${{ toJson(github.head_ref) }}
    - name: Testing env variables
      
      if: startsWith(github.ref, 'refs/heads/master')
      env:
        test1: test1-value
        test2: test2-value
        BRANCH_COMMIT_ID: ${{ toJson(github.head_ref) }}
      
      run: |
        echo $test1
        echo $BRANCH_COMMIT_ID
