name: test env variables accross jobs

on:
  push:
    tags: 
      - dev-*
      - test-*
      - prod-*       

jobs:
  set-env-variables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Code Checkout
    - name: set env variables according to ref name
      run: |
        tag_name=${GITHUB_REF}
        if [[ $tag_name == "refs/tags/test"* ]]; then
          echo "test tag"
        else
            echo "$tag_name"
        fi
      env:
        GITHUB_REF: ${{ github.ref }}
              
    - name: Run a multi-line script
      run: |
        echo ${GITHUB_REF}
        echo test
  
  test-env-from-prev-job:
    runs-on: [ubuntu-latest]
    steps:
      - name: print previous jobs ebnv var
        run: echo ${GITHUB_REF}
