name: test env variables accross jobs

on:
  push:
    tags: 
      - dev-*
      - test-*
      - prod-*       

jobs:
  set env variables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Code Checkout
    - name: set env variables according to ref name
      run: |
        tag_name={{ github.ref }}
        if [[ $tag_name == /ref/tags/test* ]]; then
          echo "test tag"
        else
            echo "$tag_name"
        fi
      
    - name: Run a multi-line script
      run: |
        echo {{ github.ref }}
        echo {{ secrets.test }}
