name: test-makefile-workflow

on:
  push:
    branches:
      - master

jobs:
  test-make:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: make file test
      run: make test
      env:
        TF_FILE_PATHS: "a b/c d"
