name: test-tag-workflow

on:
  push:
    tags:
      - PROD-MIYAZAKI-CODE-*

jobs:
  get commit id from tag name:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: printing cotext values
      run: |
        echo "github ref ${{ github.ref }}"
        export BRANCH_TAG=`printf $(cut -d- -f4 <<< ${{ github.ref }})`
	echo $BRANCH_TAG
